### ISSUE TITLE
Syntax Error in gnome 45.3

### ISSUE THREAD

**Issue by studiosusmed** [ChrisLauinger77/messagingmenu#11]
Immediately after installing the extension I get the following error:
`SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/ui/main.js:3:0`

Kernel: Linux 6.6.10-1-MANJARO
Any other information I can provide to tackle this down?

**Comment by ChrisLauinger77** [comment]
Installed it from [E.G.O.](https://extensions.gnome.org/extension/2896/messaging-menu/) ?
Make sure you have the newest version (45.0) and logout / relogin.
Then it should work ...

**Comment by ChrisLauinger77** [comment]
@studiosusmed Does it work now ? Can the issue be closed ?

**Comment by studiosusmed** [comment]
Thx Chris! It's working again. What's the problem with EGO?

**Comment by ChrisLauinger77** [comment]
> Thx Chris! It's working again. What's the problem with EGO?

No idea what you mean ? Just wonder If you downloaded the zip yourself or used EGO ? 
EGO is prefered
