### ISSUE TITLE
Nothing happens when I get new e-mails in Thunderbird

### ISSUE THREAD

**Issue by benintech** [ChrisLauinger77/messagingmenu#4]
I am using Thunderbird (Debian 11, Gnome 3.38, Thunderbird 102). Extension version 4.

Thunderbird is automatically recognized by the extension, but the icon doesn't light up when Thunderbird sends a new mail notification. I verified that the "Email notification" setting is checked.

In case it matters : my TB account is POP3.

**Comment by ChrisLauinger77** [comment]
Not sure what broke it TBH - I will have a look

**Comment by ChrisLauinger77** [comment]
I made a branch and did some refactoring to make the code better readable.
But I still don't know why it does not work - it seems gnome shell changed a lot - I need some help I think

**Comment by benintech** [comment]
Tell me if there is some log file I could provide you with...

PS : it's not an issue for me anymore, because I found a better way to display Thunderbird's info on the panel (https://github.com/Ximi1970/systray-x, an integrated Thunderbird extension). So I ended up disabling TB's notifications anyway.

**Comment by ChrisLauinger77** [comment]
It is not abouit logs - its more about understanding how gnome handles this notifications. I investigated some hours already but I lack some deeper knowledge it seems

**Comment by ChrisLauinger77** [comment]
I made some progress - I refactored the code to monitor when notifications are added / removed.
Some more testing and fine tuning is needed but I think I have it running during this week.

**Comment by ChrisLauinger77** [comment]
I checked in the new version with a completely new way to check if notifications are there.
I do not use thunderbird - I tested with evolution and it worked 4 me.
I also cannot test 3.38 as I have 43 - maybe you can test if the extension.js works on 3.38.
The prefs.js for sure will not so take only the extensioin.js If you wanna test.
